app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::auth();

Route::get('/home', 'HomeController@index');

Route::get('post/{id}', ['as'=>'home.post', 'uses'=>'AdminPostsController@post']);

Route::group(['middleware'=>'admin'], function(){

    Route::get('/admin', function(){
        return view('admin.index');
    });

    /*
     * route with resource controller for users
     */
    Route::resource('admin/users', 'AdminUsersController');

    /*
     * route with resource controller for posts
     */
    Route::resource('admin/posts', 'AdminPostsController');

    /*
     * route with resource controller for categories
     */
    Route::resource('admin/categories', 'AdminCategoryController');

    /*
     * route with resource controller for media
     */
    Route::resource('admin/media', 'AdminMediaController');

    /*
     * route with resource controller for comments on post
     */
    Route::resource('admin/comments', 'PostCommentsController');

    /*
     * route with resource controller for reply on comments
     */
    Route::resource('admin/comment/replies', 'CommentRepliesController');

//    Route::delete('delete/media', 'AdminMediaController@deleteMedia');

});

Route::group(['middleware'=>'auth'], function(){

   /*
    * for create reply on comment of post must login
    */
    Route::post('comment/reply', 'CommentRepliesController@createReply');
});

app/Comment.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Comment extends Model
{
    //
    protected $fillable=[
        'post_id',
        'author',
        'is_active',
        'email',
        'photo',
        'body'
    ];

    /*
     * comment has many replies
     */
    public function replies(){
        return $this->hasMany('App\CommentReply');
    }

    /*
     * comment belongs to post
     */
    public function post(){
        return $this->belongsTo('App\Post');
    }
}

resources/views/admin/comments/index.blade.php
@extends('layouts.admin')

@section('content')

    <h1>Comments</h1>

    @if(count($comments)>0)

      <table class="table table-hover">
          <thead>
            <tr>
              <th>Id</th>
              <th>Author</th>
              <th>Email</th>
                <th>Body</th>
            </tr>
          </thead>
          <tbody>

          @foreach($comments as $comment)

            <tr>
              <td>{{ $comment->id }}</td>
              <td>{{ $comment->author }}</td>
              <td>{{ $comment->email }}</td>
                <td>{{ $comment->body }}</td>
                <td><a href="{{ route('home.post', $comment->post->id) }}">View Post</a></td>
                <td><a href="{{ route('admin.comment.replies.show', $comment->id) }}">View Replies</a></td>
                <td>

                    @if($comment->is_active==1)

                            {!! Form::open(['method'=>'PATCH','action'=>['PostCommentsController@update', $comment->id]]) !!}

                                <input type="hidden" name="is_active" value="0">

                                <div class="form-group">
                                   {!! Form::submit('Un-approve',['class'=>'btn btn-success']) !!}
                                </div>

                            {!! Form::close() !!}

                        @else
                            {!! Form::open(['method'=>'PATCH','action'=>['PostCommentsController@update', $comment->id]]) !!}

                            <input type="hidden" name="is_active" value="1">

                            <div class="form-group">
                                {!! Form::submit('Approve',['class'=>'btn btn-info']) !!}
                            </div>

                            {!! Form::close() !!}

                        @endif

                </td>

                <td>

                        {!! Form::open(['method'=>'DELETE','action'=>['PostCommentsController@destroy', $comment->id]]) !!}

                                <div class="form-group">
                                  {!! Form::submit('Delete',['class'=>'btn btn-danger']) !!}
                                </div>

                            {!! Form::close() !!}

                </td>
            </tr>

              @endforeach
          </tbody>
        </table>

      <div class="row">
          <div class="col-sm-6 col-sm-offset-5">

              {{ $comments->links()}}

          </div>
      </div>

    @else

    <h2 class="text-center">No Comments</h2>

    @endif

@endsection

resources/views/admin/comments/show.blade.php
@extends('layouts.admin')

@section('content')

    <h1>Comments</h1>

    @if($comments)

        <table class="table table-hover">
            <thead>
            <tr>
                <th>Id</th>
                <th>Author</th>
                <th>Email</th>
                <th>Body</th>
            </tr>
            </thead>
            <tbody>

            @foreach($comments as $comment)

                <tr>
                    <td>{{ $comment->id }}</td>
                    <td>{{ $comment->author }}</td>
                    <td>{{ $comment->email }}</td>
                    <td>{{ $comment->body }}</td>
                    <td><a href="{{ route('home.post', $comment->post->id) }}">View Post</a></td>
                    <td>

                        @if($comment->is_active==1)

                            {!! Form::open(['method'=>'PATCH','action'=>['PostCommentsController@update', $comment->id]]) !!}

                            <input type="hidden" name="is_active" value="0">

                            <div class="form-group">
                                {!! Form::submit('Un-approve',['class'=>'btn btn-success']) !!}
                            </div>

                            {!! Form::close() !!}

                        @else
                            {!! Form::open(['method'=>'PATCH','action'=>['PostCommentsController@update', $comment->id]]) !!}

                            <input type="hidden" name="is_active" value="1">

                            <div class="form-group">
                                {!! Form::submit('Approve',['class'=>'btn btn-info']) !!}
                            </div>

                            {!! Form::close() !!}

                        @endif

                    </td>

                    <td>

                        {!! Form::open(['method'=>'DELETE','action'=>['PostCommentsController@destroy', $comment->id]]) !!}

                        <div class="form-group">
                            {!! Form::submit('Delete',['class'=>'btn btn-danger']) !!}
                        </div>

                        {!! Form::close() !!}

                    </td>
                </tr>

            @endforeach
            </tbody>
        </table>

    @else

        <h2 class="text-center">No Comments</h2>

    @endif

@endsection