app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::auth();

Route::get('/home', 'HomeController@index');

Route::get('post/{id}', ['as'=>'home.post', 'uses'=>'AdminPostsController@post']);

Route::group(['middleware'=>'admin'], function(){

    Route::get('/admin', function(){
        return view('admin.index');
    });

    /*
     * route with resource controller for users
     */
    Route::resource('admin/users', 'AdminUsersController');

    /*
     * route with resource controller for posts
     */
    Route::resource('admin/posts', 'AdminPostsController');

    /*
     * route with resource controller for categories
     */
    Route::resource('admin/categories', 'AdminCategoryController');

    /*
     * route with resource controller for media
     */
    Route::resource('admin/media', 'AdminMediaController');

    /*
     * route with resource controller for comments on post
     */
    Route::resource('admin/comments', 'PostCommentsController');

    /*
     * route with resource controller for reply on comments
     */
    Route::resource('admin/comment/replies', 'CommentRepliesController');

//    Route::delete('delete/media', 'AdminMediaController@deleteMedia');

});

Route::group(['middleware'=>'auth'], function(){

   /*
    * for create reply on comment of post must login
    */
    Route::post('comment/reply', 'CommentRepliesController@createReply');
});

app/Post.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    // mass assignment
    protected $fillable=[
      'category_id',
        'photo_id',
        'title',
        'body'
    ];

    /*
     * realtion with user model
     */
    public function user(){
        return $this->belongsTo('App\User');
    }

    /*
     * relation with photo model
     */
    public function photo(){
        return $this->belongsTo('App\Photo');
    }

    /*
     * relation with catagory model
     */
    public function category(){
        return $this->belongsTo('App\Category');
    }

    /*
     * post relationship with comment
     */
    public function comments(){
        return $this->hasMany('App\Comment');
    }

    /*
     * function for placeholder image
     */
    public function photoPlaceholder(){
        return "http://placehol.it/200x700";
    }
}

resources/views/admin/posts/create.blade.php
@extends('layouts.admin')


@section('content')

    @include('includes.tinyeditor')

    <h1>Create Post</h1>

    <div class="row">

         {!! Form::open(['method'=>'POST', 'action'=> 'AdminPostsController@store', 'files'=>true]) !!}

           <div class="form-group">
                 {!! Form::label('title', 'Title:') !!}
                 {!! Form::text('title', null, ['class'=>'form-control'])!!}
           </div>

            <div class="form-group">
                {!! Form::label('category_id', 'Category:') !!}
                {!! Form::select('category_id', [''=>'Choose Categories'] + $cate, null, ['class'=>'form-control'])!!}
            </div>


            <div class="form-group">
                {!! Form::label('photo_id', 'Photo:') !!}
                {!! Form::file('photo_id', null,['class'=>'form-control'])!!}
             </div>


            <div class="form-group">
                {!! Form::label('body', 'Description:') !!}
                {!! Form::textarea('body', null, ['class'=>'form-control'])!!}
            </div>




             <div class="form-group">
                {!! Form::submit('Create Post', ['class'=>'btn btn-primary']) !!}
             </div>

           {!! Form::close() !!}

    </div>

    {{--display error--}}
    <div class="row">

        @include('includes.form_error')

    </div>




@stop

resources/views/admin/posts/edit.blade.php
@extends('layouts.admin')

@section('content')

    @include('includes.tinyeditor')

{{--edit post--}}

<h1>Edit Post</h1>
    
    <div class="row">

        <div class="col-sm-3">

            <img src="{{$post->photo ? $post->photo->file : $post->photoPlaceholder()}}" alt="" class="img-responsive">
             
            </div>

        <div class="col-sm-9">
   
        {!! Form::model($post, ['method'=>'PATCH', 'action'=> ['AdminPostsController@update', $post->id], 'files'=>true]) !!}

        <div class="form-group">
            {!! Form::label('title', 'Title:') !!}
            {!! Form::text('title', null, ['class'=>'form-control'])!!}
        </div>

        <div class="form-group">
            {!! Form::label('category_id', 'Category:') !!}
            {!! Form::select('category_id',  $cate, null, ['class'=>'form-control'])!!}
        </div>


        <div class="form-group">
            {!! Form::label('photo_id', 'Photo:') !!}
            {!! Form::file('photo_id', null,['class'=>'form-control'])!!}
        </div>


        <div class="form-group">
            {!! Form::label('body', 'Description:') !!}
            {!! Form::textarea('body', null, ['class'=>'form-control'])!!}
        </div>

        <div class="form-group">
            {!! Form::submit('Update Post', ['class'=>'btn btn-primary col-sm-6']) !!}
        </div>

        {!! Form::close() !!}


        {!! Form::open(['method'=>'DELETE', 'action'=> ['AdminPostsController@destroy', $post->id]]) !!}

             <div class="form-group">
                 {!! Form::submit('Delete Post', ['class'=>'btn btn-danger col-sm-6']) !!}
             </div>
        {!! Form::close() !!}


        </div>


    </div>


    <div class="row">

        @include('includes.form_error')

    </div>

@stop

resources/views/admin/posts/index.blade.php
@extends('layouts.admin')

@section('content')

    <h1>Posts</h1>

    {{-- DISPALY ALL POSTS --}}
    <table class="table">
       <thead>
         <tr>
             <th>Id</th>
             <th>Photo</th>
             <th>Owner</th>
             <th>Category</th>
             <th>Title</th>
             <th>body</th>
             <th>Post link</th>
             <th>Comments</th>
             <th>Created at</th>
             <th>Update</th>
        </thead>
        <tbody>

        @if($posts)

            @foreach($posts as $post)

          <tr>
              <td>{{$post->id}}</td>
              <td><img height="50" src="{{$post->photo ? $post->photo->file : 'http://placehold.it/400x400' }} " alt=""></td>
              <td><a href="{{route('admin.posts.edit', $post->id) }}">{{$post->user->name}}</a></td>
              <td>{{$post->category ? $post->category->name : 'Uncategorized'}}</td>
              <td>{{$post->title}}</td>
              <td>{{str_limit($post->body, 30)}}</td>
              <td><a href="{{route('home.post', $post->id)}}">View Post</a></td>
              <td><a href="{{route('admin.comments.show', $post->id)}}">View Comments</a></td>
              <td>{{$post->created_at->diffForhumans()}}</td>
              <td>{{$post->updated_at->diffForhumans()}}</td>

          </tr>

            @endforeach

            @endif

       </tbody>
     </table>



    <div class="row">
        <div class="col-sm-6 col-sm-offset-5">

            {{ $posts->links()}}

        </div>
    </div>



@stop