app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::auth();

Route::get('/home', 'HomeController@index');

Route::get('post/{id}', ['as'=>'home.post', 'uses'=>'AdminPostsController@post']);

Route::group(['middleware'=>'admin'], function(){

    Route::get('/admin', function(){
        return view('admin.index');
    });

    /*
     * route with resource controller for users
     */
    Route::resource('admin/users', 'AdminUsersController');

    /*
     * route with resource controller for posts
     */
    Route::resource('admin/posts', 'AdminPostsController');

    /*
     * route with resource controller for categories
     */
    Route::resource('admin/categories', 'AdminCategoryController');

    /*
     * route with resource controller for media
     */
    Route::resource('admin/media', 'AdminMediaController');

    /*
     * route with resource controller for comments on post
     */
    Route::resource('admin/comments', 'PostCommentsController');

    /*
     * route with resource controller for reply on comments
     */
    Route::resource('admin/comment/replies', 'CommentRepliesController');

//    Route::delete('delete/media', 'AdminMediaController@deleteMedia');

});

Route::group(['middleware'=>'auth'], function(){

   /*
    * for create reply on comment of post must login
    */
    Route::post('comment/reply', 'CommentRepliesController@createReply');
});

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    //

    protected $fillable=[
        'name'
    ];
}

resources/views/admin/categories/edit.blade.php
@extends('layouts.admin')

@section('content')

    <h1>Categories</h1>

    <div class="col-sm-6">

        {!! Form::model($category, ['method'=>'PATCH', 'action'=> ['AdminCategoryController@update', $category->id]]) !!}
        <div class="form-group">
            {!! Form::label('name', 'Name:') !!}
            {!! Form::text('name', null, ['class'=>'form-control'])!!}
        </div>

        <div class="form-group">
            {!! Form::submit('Update Category', ['class'=>'btn btn-primary col-sm-6 ']) !!}
        </div>
        {!! Form::close() !!}


        {!! Form::open(['method'=>'DELETE', 'action'=> ['AdminCategoryController@destroy', $category->id]]) !!}


        <div class="form-group">
            {!! Form::submit('Delete Category', ['class'=>'btn btn-danger col-sm-6']) !!}
        </div>
        {!! Form::close() !!}



    </div>




    <div class="col-sm-6">






    </div>





@stop

resources/views/admin/categories/index.blade.php
@extends('layouts.admin')

@section('content')

    <h1>Categories</h1>

    <div class="col-sm-6">

        {!! Form::open(['method'=>'POST', 'action'=> 'AdminCategoryController@store']) !!}
             <div class="form-group">
                 {!! Form::label('name', 'Name:') !!}
                 {!! Form::text('name', null, ['class'=>'form-control'])!!}
             </div>

             <div class="form-group">
                 {!! Form::submit('Create Category', ['class'=>'btn btn-primary']) !!}
             </div>
        {!! Form::close() !!}



    </div>




    <div class="col-sm-6">


        @if($categories)


            <table class="table">
                <thead>
                <tr>
                    <th>id</th>
                    <th>Name</th>
                    <th>Created date</th>
                </tr>
                </thead>
                <tbody>

                @foreach($categories as $category)

                    <tr>
                        <td>{{$category->id}}</td>
                        <td><a href="{{route('admin.categories.edit', $category->id)}}">{{$category->name}}</a></td>
                        <td>{{$category->created_at ? $category->created_at->diffForHumans() : 'no date'}}</td>
                    </tr>
                @endforeach

                </tbody>
            </table>

            <div class="row">
                <div class="col-sm-6 col-sm-offset-5">

                    {{ $categories->links()}}

                </div>
            </div>

        @endif



    </div>





@stop